#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Index page
echo "Holberton School" | sudo tee /var/www/html/index

# Redirect to Freudian psychoanalysis page
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=i0OoNNh9j2U&ab_channel=PHILO-notes/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
