#!/usr/bin/env bash
# Script that setup a nginx web server on our server + redirection + 404.

apt update -y && apt upgrade -y
apt install nginx -y

# Index page
echo "Hello World!" >/var/www/html/index.nginx-debian.html

# Redirect to Freudian psychoanalysis page
sed -i '/listen \[::\]:80 default_server;/a\rewrite ^\/redirect_me https://www.youtube.com/watch?v=i0OoNNh9j2U&ab_channel=PHILO-notes permanent;' /etc/nginx/sites-available/default

# 404 Page not Found
echo "Ceci n'est pas une page" >/var/www/html/404.html
sed -i '/dQw4w9WgXcQ permanent;$/a\error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart

