#!/usr/bin/env bash
# Configures a server with HAProxy

apt update -y && apt upgrade -y
apt install haproxy=1.6.\* -y

echo "ENABLED=1" >>/etc/default/haproxy

haproxy_cfg="\nbackend web-backend\n\tbalance roundrobin\n\tserver 101871-web-01 54.146.72.69:80 check\n\tserver 101871-web-02 100.26.236.132:80 check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo -e "$haproxy_cfg" >>/etc/haproxy/haproxy.cfg

service haproxy restart
